name: GameCore
version: ${version}
authors:
  - malfact
main: net.malfact.gamecore.GameCore
api-version: '1.20'
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false
permissions:
  gamecore.*:
    default: op
    children:
      gamecore.admin.*: true
      gamecore.player.*: true
  gamecore.admin:
    default: false
    children:
      gamecore.reload: true
      gamecore.save: true
      gamecore.queue.admin: true
      gamecore.team.admin: true
  gamecore.player:
    default: false
    children:
      gamecore.queue.player: true
      gamecore.team.player: true
  gamecore.queue.*:
    default: op
    children:
      gamecore.queue.admin: true
      gamecore.queue.player: true
  gamecore.queue.admin:
    default: false
    children:
      gamecore.queue.add: true
      gamecore.queue.remove: true
      gamecore.queue.join.other: true
      gamecore.queue.leave.other: true
      gamecore.queue.list: true
      gamecore.queue.pop: true
  gamecore.queue.player:
    default: false
    children:
      gamecore.queue.join: true
      gamecore.queue.leave: true
  gamecore.team.*:
    default: op
    children:
      gamecore.team.admin: true
      gamecore.team.player: true
  gamecore.team.admin:
    default: false
    children:
      gamecore.team.add: true
      gamecore.team.remove: true
      gamecore.team.join.other: true
      gamecore.team.leave.other: true
      gamecore.team.list: true
      gamecore.team.modify: true
      gamecore.team.empty: true
  gamecore.team.player:
    default: false
    children:
      gamecore.team.join: true
      gamecore.team.leave: true
  gamecore.ignore-spawn-on-join:
    default: false